
git:
  strategy: clone
  depth: 3
  quiet: true

dist: xenial
language: bash

env:
  global: # remove this global variable to run on all files
    #CHANGED_FILES="$(git diff --name-only ${TRAVIS_BRANCH}..HEAD --)"

matrix:
  include:
     script:
        - echo $CHANGED_FILES
        - cd
        - git clone https://${GHE_TOKEN}:x-oauth-basic@github.ibm.com/ibmcloud/ibm-vale.git /tmp/vale
        - cd /tmp/vale
        #- rm .vale.ini && cp ${TRAVIS_BUILD_DIR}/.vale.ini .vale.ini
        - wget https://github.com/errata-ai/vale/releases/download/v2.28.0/vale_2.28.0_Linux_64-bit.tar.gz
        - mkdir bin && tar -xvzf vale_2.28.0_Linux_64-bit.tar.gz -C bin
        - export PATH=./bin:"$PATH"
        - do vale --minAlertLevel=error $TRAVIS_BUILD_DIR/"$CHANGED_FILES"; done
