# .github/workflows/vale.yml
name: Check AsciiDoc with vale

on:
  workflow_dispatch:
  push:
    paths:
      - 'posts/**/*.adoc'
  pull_request:
    paths:
      - 'posts/**/*.adoc'
jobs:
  vale:
    name: Vale Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Install Vale
        run: |
          curl -fsSL https://github.com/errata-ai/vale/releases/latest/download/vale_Linux_64-bit.tar.gz | tar -xz
          sudo mv vale /usr/local/bin

      - name: Run Vale on .adoc files
        run: |
          mkdir -p vale-results
          vale --output=JSON --glob='*.adoc' > vale-results/vale-output.json 

      - name: Upload Vale output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vale-results
          path: vale-results/vale-output.json    
