# .github/workflows/vale.yml
name: Check Prose with Vale

# This action runs on pushes and pull requests to the main branch.
# You can customize this to fit your branching strategy.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prose:
    name: Runner
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository's code so the action can access it.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Run the Vale GitHub Action.
      # This action automatically downloads Vale and runs it against your files.
      # It will use the configuration file (.vale.ini) from your repository.
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          # You can specify which files to lint.
          # The default is to lint all files recognized by Vale ('*').
          # For example, to only lint Markdown files, you could use:
          # files: '["*.md"]'
          files: '["*.adoc"]'
      

        # The action can post review comments directly on your pull requests.
        # This requires a GITHUB_TOKEN with appropriate permissions.
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
