# .github/workflows/vale.yml
name: Check AsciiDoc with vale

on:
  workflow_dispatch:
  push:
    paths:
      - 'posts/**/*.adoc'
  pull_request:
    paths:
      - 'posts/**/*.adoc'
jobs:
  vale:
    name: Vale Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Run Vale on AsciiDoc files
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: posts/test.adoc
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      